### ISSUE TITLE
lattice.StepEvent do not need alpha?

### ISSUE THREAD

**Issue by 0ncorhynchus** [ecell/ecell4#35]
A parameter alpha is owned by LatticeSimulator and StepEvent.
When LatticeSimulator generate a StepEvent instance, alpha of it is set to simulator's value.
While alpha in the simulator can be changed, that in StepEvent can not.
Once a StepEvent instance is generated, alpha in the simulator is changed and values of alpha in them may be different.
This difference is wrong to the simulation.

On the other hand, a StepEvent instance has the pointer of LatticeSimulator which owns it.
So, the instance can be see the value of alpha of LatticeSimulator via LatticeSimulator::get_alpha().

**Comment by kaizu** [comment]
I think that StepEvent should rather have alpha, but LatticeSimulator should not because an appropriate alpha value differs among species.
Ideally, alpha should be settable for each StepEvent (manually or automatically), but now there is only one manual interface, LatticeSimulator::set_alpha.
If the inconsistency between StepEvent::alpha and LatticeSimulator::alpha is of a problem, LatticeSimulator should behave like:

```cxx
void LatticeSimulator::set_alpha(const Real alpha)
{
    for (auto& ev : events_)
    {
        auto stepev = dynamic_cast<StepEvent*>(ev);
        if (stepev) stepev.set_alpha(alpha);
    }
}
```

Events in a scheduler might be immutable. Use ``update`` for the case.
What do you think?

**Comment by 0ncorhynchus** [comment]
I see. There is no problem now. I was just confused.
I think it's better that each StepEvent has its own alpha value too.
